# Generated by Django 3.1.5 on 2021-09-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
