# Generated by Django 3.1.5 on 2021-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210930_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTitulos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lei', models.CharField(max_length=20)),
                ('texto', models.TextField()),
            ],
            options={
                'db_table': 'api_titulos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='titulos',
        ),
    ]
