# Generated by Django 3.1.5 on 2021-10-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210930_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.TextField(blank=True, null=True)),
                ('sec', models.TextField(blank=True, null=True)),
                ('subsec', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artigo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capitulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel2',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.TextField(blank=True, null=True)),
                ('sec', models.TextField(blank=True, null=True)),
                ('subsec', models.TextField(blank=True, null=True)),
                ('artigo', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel3',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.TextField(blank=True, null=True)),
                ('sec', models.TextField(blank=True, null=True)),
                ('subsec', models.TextField(blank=True, null=True)),
                ('artigo', models.TextField(blank=True, null=True)),
                ('nivel2', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel4',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.TextField(blank=True, null=True)),
                ('sec', models.TextField(blank=True, null=True)),
                ('subsec', models.TextField(blank=True, null=True)),
                ('artigo', models.TextField(blank=True, null=True)),
                ('nivel2', models.TextField(blank=True, null=True)),
                ('nivel3', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subsecao',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.IntegerField(blank=True, null=True)),
                ('sec', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subsecao',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='apititulos',
            table='titulos',
        ),
    ]
