# Generated by Django 3.1.5 on 2021-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('lei', models.TextField(blank=True, null=True)),
                ('titulo', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.TextField(blank=True, null=True)),
                ('sec', models.TextField(blank=True, null=True)),
                ('subsec', models.TextField(blank=True, null=True)),
                ('artigo', models.TextField(blank=True, null=True)),
                ('nivel2', models.TextField(blank=True, null=True)),
                ('nivel3', models.TextField(blank=True, null=True)),
                ('nivel4', models.TextField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Questao',
                'managed': False,
            },
        ),
    ]
